CREATE TABLE Department (
    dept_id NUMBER PRIMARY KEY,
    dept_name VARCHAR2(50)
);

CREATE TABLE Jobs(
    job_id NUMBER PRIMARY KEY,
    job_title VARCHAR2(50),
    min_salary NUMBER(10, 2) NOT NULL,
    max_salary NUMBER(10, 2) NOT NULL
);

CREATE TABLE Employee (
    emp_id NUMBER PRIMARY KEY,
    emp_name VARCHAR2(100),
    email VARCHAR2(50),
    hire_date DATE,
    salary NUMBER,
    dept_id NUMBER,
    job_id NUMBER,
    manager_id NUMBER,
    FOREIGN KEY (dept_id) REFERENCES Department(dept_id),
    FOREIGN KEY (job_id) REFERENCES Jobs(job_id),
    FOREIGN KEY (manager_id) REFERENCES Employee(emp_id)
);

CREATE TABLE Payroll (
    payroll_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id NUMBER NOT NULL,
    pay_period_start_date DATE NOT NULL,
    pay_period_end_date DATE NOT NULL,
    basic_salary NUMBER(10, 2) NOT NULL,
    allowances NUMBER(10, 2) DEFAULT 0,
    deductions NUMBER(10, 2) DEFAULT 0,
    tax_amount NUMBER(10, 2) DEFAULT 0,
    net_salary NUMBER(10, 2) NOT NULL,
    payment_date DATE NOT NULL,
    payment_method VARCHAR2(50),
    FOREIGN KEY (emp_id) REFERENCES Employee(emp_id)
);
CREATE TABLE payroll_log (
    log_id NUMBER GENERATED ALWAYS AS IDENTITY,
    log_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    log_message VARCHAR2(400)
);
